# Generated by Django 3.2.24 on 2024-03-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_contact_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mesage',
            new_name='message',
        ),
    ]
