# Generated by Django 3.2.24 on 2024-03-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_rename_mesage_contact_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
