# Generated by Django 3.2.24 on 2024-03-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
