# Generated by Django 3.2.24 on 2024-03-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_product_records'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name': 'Records'},
        ),
        migrations.AddField(
            model_name='records',
            name='release_date',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
