# Generated by Django 3.2.24 on 2024-03-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_records_is_new_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='category',
        ),
        migrations.AddField(
            model_name='records',
            name='category',
            field=models.ManyToManyField(blank=True, to='records.Category'),
        ),
    ]
