# Generated by Django 3.2.24 on 2024-03-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20240310_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='is_clearance',
            field=models.BooleanField(default=False, verbose_name='Is Clearance'),
        ),
        migrations.AddField(
            model_name='records',
            name='is_deal',
            field=models.BooleanField(default=False, verbose_name='Is Deal'),
        ),
    ]
