# Generated by Django 3.2.24 on 2024-03-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20240310_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='release_date',
            new_name='releasedate',
        ),
    ]
