# Generated by Django 3.2.24 on 2024-03-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_records_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='description',
            field=models.TextField(),
        ),
    ]
